version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  console_err:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr
  app_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ../logs/application.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console, app_info]
    propagate: yes
root:
  level: DEBUG
  handlers: [console_err]